Interparking/Interparking.WeppApp/Controllers/RouteController.cs
using AutoMapper;
using Interparking.DAL.Abstraction;
using Interparking.DAL.Model;
using Interparking.WeppApp.Command;
using Interparking.WeppApp.Infrastructure.Principal;
using Interparking.WeppApp.Models.Routes;
using Interparking.WeppApp.Query;
using MediatR;
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace Interparking.WeppApp.Controllers
{
    [Authorize]
    public class RouteController : Controller
    {
        IMediator mediator;
        IMapper mapper;
        IParkingRepository parkingRepository;

        public RouteController(IMediator mediator, IMapper mapper, IParkingRepository parkingRepository)
        {
            this.mediator = mediator;
            this.mapper = mapper;
            this.parkingRepository = parkingRepository;
        }
        // GET: Route
        public ActionResult Index()
        {
            var parkings = parkingRepository.GetALL().GetAwaiter().GetResult();
            var model = new RouteViewModel();
            
            model.Parkings = parkings.Select(x => new SelectListItem { 
            Text = x.Name,
            Value = x.Address
            }).ToList();

            return View(model);
        }


        public ActionResult CreateRoute(RouteViewModel route)
        {
            var model = mapper.Map<CreateRouteCommand>(route);
            model.IdClient = (HttpContext.User as CustomPrincipal).Id;
            mediator.Send(model);
            return RedirectToAction("Index");
        }

        public ActionResult Routes()
        {
            var userId = (HttpContext.User as CustomPrincipal).Id;
            var routes = mediator.Send(new GetRoutesByUserIdQuery { user = new UserRequestById { UserId = userId } }).GetAwaiter().GetResult();

            //var model = mapper.Map<RouteViewModel>(routes);
            var model = routes.Select(x => new RouteViewModel
            {
                Id = x.Id,
                Departure = x.Departure,
                Destination = x.Destination,
                IdClient = x.IdClient,
                LatDeparture = x.LatDeparture,
                LatDestination = x.LatDestination,
                LongDeparture = x.LongDeparture,
                LongDestination = x.LongDestination,
                Fuel = x.Fuel,
                Distance= x.Distance
                
            });
            return View(model);
        }
        public ActionResult UpdateRoute(int routeId)
        {
            var model = mediator.Send(
                new GetRouteByRouteIDQuery
                { 
                    IdRoute = routeId
                }).GetAwaiter().GetResult();

            var viewmodel = mapper.Map<RouteViewModel>(model);

            return View(viewmodel);
        }

        [HttpPost]
        public ActionResult UpdateRoute(RouteViewModel route)
        {
            return View();
        }

    }
}

Interparking/Interparking.WeppApp/Controllers/UserController.cs
using Interparking.DAL.Abstraction;
using Interparking.DAL.Model;
using Interparking.WeppApp.Command;
using Interparking.WeppApp.Models.User;
using MediatR;
using Ninject;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Interparking.WeppApp.Controllers
{
    [AllowAnonymous]
    public class UserController : Controller
    {
        private readonly IMediator mediator;


        public UserController(IMediator mediator)
        {
            this.mediator = mediator;
        }

        // GET: User
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddUser(UserViewModel user)
        {
            if (ModelState.IsValid)
            {
                mediator.Send(new CreateUserCommand
                {
                    email = user.Email,
                    name = user.Name,
                    password = user.Password
                });

                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");

        }

    }
}

Interparking/Interparking.WeppApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nom d'application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Accueil", "Index", "Home")</li>
                    <li>@Html.ActionLink("Add Route", "Index", "Route")</li>
                    <li>@Html.ActionLink("List of Route", "Routes", "Route")</li>
                    <li>@Html.ActionLink("Add User", "Index", "User")</li>
                    <li>@Html.ActionLink("Log Out", "Logout", "Account")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mon application ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>